import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { prepareInvoiceForEmail } from "./invoice-send";
const m = vi.hoisted(() => ({
  from: vi.fn(),
  download: vi.fn(),
  finalize: vi.fn(),
  archive: vi.fn(),
  hash: vi.fn(),
}));
vi.mock("@/integrations/supabase/client", () => ({
  supabase: { from: m.from, storage: { from: () => ({ download: m.download }) } },
}));
vi.mock("./gobd", () => ({
  finalizeDocument: m.finalize,
  archiveDocumentPdf: m.archive,
  sha256Hex: m.hash,
}));
vi.mock("./storage", () => ({ FILES_BUCKET: "synthetic-bucket" }));
const generated = new TextEncoder().encode("%PDF-1.7 generated");
const original = new TextEncoder().encode("%PDF-1.7 original");
const id = "synthetic-id",
  number = "RE-2026-0001";
const base = { id, number, locked_at: null, pdf_path: null, pdf_sha256: null, archived_at: null };
function database(record = base, pendingError: Error | null = null) {
  m.from.mockImplementation(() => {
    let updating = false;
    const query = {
      select: vi.fn(() => query),
      eq: vi.fn(() => query),
      is: vi.fn(() => query),
      update: vi.fn(() => {
        updating = true;
        return query;
      }),
      single: vi.fn(async () =>
        updating
          ? { data: pendingError ? null : { id }, error: pendingError }
          : { data: record, error: null },
      ),
    };
    return query;
  });
}
beforeEach(() => {
  database();
  m.finalize.mockResolvedValue({ id, number });
  m.archive.mockResolvedValue({ path: "test", hash: "abc" });
  m.hash.mockResolvedValue("abc");
  m.download.mockResolvedValue({ data: new Blob([original]), error: null });
});
afterEach(() => vi.resetAllMocks());
describe("invoice preparation before sending", () => {
  it("archives exactly the generated bytes after finalization", async () => {
    expect(await prepareInvoiceForEmail(id, number, generated)).toBe(generated);
    expect(m.archive).toHaveBeenCalledWith({ id, number }, generated);
    expect(m.finalize.mock.invocationCallOrder[0]).toBeLessThan(
      m.archive.mock.invocationCallOrder[0]!,
    );
  });
  it("blocks sending when archive upload fails", async () => {
    m.archive.mockRejectedValue(new Error("archive failed"));
    await expect(prepareInvoiceForEmail(id, number, generated)).rejects.toThrow("archive failed");
  });
  it("blocks sending when the pending status cannot be recorded", async () => {
    database(base, new Error("status failed"));
    await expect(prepareInvoiceForEmail(id, number, generated)).rejects.toThrow("status failed");
  });
  it("never sends PDF bytes bearing a stale official number", async () => {
    m.finalize.mockResolvedValue({ id, number: "RE-2026-0002" });
    await expect(prepareInvoiceForEmail(id, number, generated)).rejects.toThrow("Rechnungsnummer");
    expect(m.archive).not.toHaveBeenCalled();
  });
  it("retries using the verified original without re-finalizing or re-archiving", async () => {
    database({
      ...base,
      locked_at: "2026-01-01",
      pdf_path: "test/original.pdf",
      pdf_sha256: "abc",
      archived_at: "2026-01-01",
    } as never);
    expect(await prepareInvoiceForEmail(id, number, generated)).toEqual(original);
    expect(m.finalize).not.toHaveBeenCalled();
    expect(m.archive).not.toHaveBeenCalled();
  });
  it.each(["missing", "hash", "not-pdf"])("blocks a damaged archive (%s)", async (condition) => {
    database({
      ...base,
      locked_at: "2026-01-01",
      pdf_path: "test/original.pdf",
      pdf_sha256: "abc",
      archived_at: "2026-01-01",
    } as never);
    if (condition === "missing")
      m.download.mockResolvedValue({ data: null, error: new Error("missing") });
    if (condition === "hash") m.hash.mockResolvedValue("wrong");
    if (condition === "not-pdf")
      m.download.mockResolvedValue({ data: new Blob(["not-pdf"]), error: null });
    await expect(prepareInvoiceForEmail(id, number, generated)).rejects.toThrow();
    expect(m.archive).not.toHaveBeenCalled();
  });
  it("does not fabricate an original for a locked invoice without an archive", async () => {
    database({ ...base, locked_at: "2026-01-01" } as never);
    await expect(prepareInvoiceForEmail(id, number, generated)).rejects.toThrow("Original-PDF");
    expect(m.finalize).not.toHaveBeenCalled();
    expect(m.archive).not.toHaveBeenCalled();
  });
});
