import { usePlanningData } from "./usePlanningData";
import { usePlanningEdits } from "./usePlanningEdits";
import { usePlanningCoverage } from "./usePlanningCoverage";

import { type CalculationPlanSeed } from "./shared";

export function useArbeitsplanungState({
  initialPlan,
}: {
  initialPlan?: CalculationPlanSeed | undefined;
}) {
  const {
    absences,
    absencesError,
    assignEmployeeId,
    assignProjectId,
    assignmentsError,
    cellDayHours,
    cellErrors,
    cellHours,
    cellTimes,
    customers,
    customersError,
    draft,
    dragEmployeeId,
    employees,
    employeesError,
    filter,
    handleEmployeeDrop,
    key,
    map,
    monday,
    objects,
    openAssignment,
    projectsError,
    queryClient,
    quickAssign,
    release,
    releaseLoading,
    releaseWeek,
    savedTimes,
    seedBreakMinutes,
    seedEmployeeId,
    seedHoursPerVisit,
    seedProject,
    seedStartTime,
    seedVisitsPerWeek,
    setAssignEmployeeId,
    setAssignProjectId,
    setCellErrors,
    setDraft,
    setDragEmployeeId,
    setFilter,
    setMonday,
    setQuickAssign,
    setSeedBreakMinutes,
    setSeedEmployeeId,
    setSeedStartTime,
    weekEnd,
    weekStart,
    withdrawRelease,
  } = usePlanningData({ initialPlan });

  const {
    applyCalculationPlan,
    applyWeekTimes,
    clearWeekTimes,
    copyPreviousWeek,
    dirtyKeys,
    employeeTotal,
    projectTotal,
    saveAll,
    setDayTime,
    visibleProjects,
  } = usePlanningEdits({
    cellHours,
    customers,
    draft,
    employees,
    filter,
    initialPlan,
    key,
    map,
    monday,
    objects,
    queryClient,
    savedTimes,
    seedBreakMinutes,
    seedEmployeeId,
    seedHoursPerVisit,
    seedProject,
    seedStartTime,
    seedVisitsPerWeek,
    setCellErrors,
    setDraft,
    setFilter,
    weekEnd,
    weekStart,
  });

  const {
    absenceAssignments,
    applyReplacement,
    cellErrorList,
    grandTotal,
    loadError,
    overtimeWarnings,
    planningConflicts,
    replacementCandidates,
  } = usePlanningCoverage({
    absences,
    absencesError,
    assignmentsError,
    cellDayHours,
    cellErrors,
    cellTimes,
    customersError,
    draft,
    employeeTotal,
    employees,
    employeesError,
    key,
    map,
    monday,
    objects,
    projectsError,
    savedTimes,
    setDraft,
    weekStart,
  });

  return {
    ready: true as const,
    absenceAssignments,
    applyCalculationPlan,
    applyReplacement,
    applyWeekTimes,
    assignEmployeeId,
    assignProjectId,
    cellDayHours,
    cellErrorList,
    cellHours,
    cellTimes,
    clearWeekTimes,
    copyPreviousWeek,
    dirtyKeys,
    dragEmployeeId,
    employeeTotal,
    employees,
    filter,
    grandTotal,
    handleEmployeeDrop,
    initialPlan,
    loadError,
    monday,
    objects,
    openAssignment,
    overtimeWarnings,
    planningConflicts,
    projectTotal,
    queryClient,
    quickAssign,
    release,
    releaseLoading,
    releaseWeek,
    replacementCandidates,
    saveAll,
    seedBreakMinutes,
    seedEmployeeId,
    seedHoursPerVisit,
    seedProject,
    seedStartTime,
    seedVisitsPerWeek,
    setAssignEmployeeId,
    setAssignProjectId,
    setDayTime,
    setDragEmployeeId,
    setFilter,
    setMonday,
    setQuickAssign,
    setSeedBreakMinutes,
    setSeedEmployeeId,
    setSeedStartTime,
    visibleProjects,
    weekEnd,
    weekStart,
    withdrawRelease,
  };
}
export type ArbeitsplanungState = Extract<
  ReturnType<typeof useArbeitsplanungState>,
  { ready: true }
>;
