import { useProjectData } from "./useProjectData";
import { useProjectActions } from "./useProjectActions";
import { useProjectControlling } from "./useProjectControlling";

export function useProjektDetailState() {
  const {
    addRoom,
    analyzing,
    assignEmployee,
    assignOpen,
    assignRole,
    assignments,
    controllingDocuments,
    controllingExpenses,
    controllingMonth,
    customerId,
    customerProjects,
    employees,
    id,
    invalidate,
    items,
    monthDate,
    patchItem,
    patchProject,
    patchRoom,
    project,
    projectCustomer,
    qmCases,
    removeRoom,
    roomDialog,
    rooms,
    runAnalyze,
    scanResult,
    setAnalyzing,
    setAssignEmployee,
    setAssignOpen,
    setAssignRole,
    setControllingMonth,
    setRoomDialog,
    setScanResult,
    timeEntries,
  } = useProjectData();

  const { addItem, applyScan, assign, handleUploaded, removeItem, unassign } = useProjectActions({
    assignEmployee,
    assignRole,
    id,
    invalidate,
    items,
    patchProject,
    project,
    rooms,
    runAnalyze,
    setAnalyzing,
    setAssignEmployee,
    setAssignOpen,
    setScanResult,
  });

  if (!project)
    return {
      ready: false as const,
      fallback: <p className="text-muted-foreground">Projekt wird geladen …</p>,
    };

  const {
    actualHours,
    aiHighlights,
    aiRequirements,
    confirmedRooms,
    contribution,
    costPerHour,
    derivedFacts,
    effectiveProjectAddress,
    expected,
    hasAnalysis,
    history,
    hourVariance,
    isTender,
    linkedCustomerEmail,
    linkedCustomerName,
    linkedCustomerPhone,
    marginPercent,
    marginStatus,
    materialAndOtherCosts,
    openCritical,
    plannedHours,
    revenueNet,
    revenuePerHour,
    topCover,
    totalCosts,
    totalSqm,
    trendRows,
    wageCosts,
  } = useProjectControlling({
    assignments,
    controllingDocuments,
    controllingExpenses,
    controllingMonth,
    customerId,
    customerProjects,
    id,
    items,
    monthDate,
    project,
    projectCustomer,
    rooms,
    timeEntries,
  });

  return {
    ready: true as const,
    actualHours,
    addItem,
    addRoom,
    aiHighlights,
    aiRequirements,
    analyzing,
    applyScan,
    assign,
    assignEmployee,
    assignOpen,
    assignRole,
    assignments,
    confirmedRooms,
    contribution,
    controllingMonth,
    costPerHour,
    derivedFacts,
    effectiveProjectAddress,
    employees,
    expected,
    handleUploaded,
    hasAnalysis,
    history,
    hourVariance,
    id,
    isTender,
    items,
    linkedCustomerEmail,
    linkedCustomerName,
    linkedCustomerPhone,
    marginPercent,
    marginStatus,
    materialAndOtherCosts,
    openCritical,
    patchItem,
    patchProject,
    patchRoom,
    plannedHours,
    project,
    qmCases,
    removeItem,
    removeRoom,
    revenueNet,
    revenuePerHour,
    roomDialog,
    rooms,
    scanResult,
    setAssignEmployee,
    setAssignOpen,
    setAssignRole,
    setControllingMonth,
    setRoomDialog,
    setScanResult,
    timeEntries,
    topCover,
    totalCosts,
    totalSqm,
    trendRows,
    unassign,
    wageCosts,
  };
}
export type ProjektDetailState = Extract<ReturnType<typeof useProjektDetailState>, { ready: true }>;
