/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RechtlichesRouteImport } from './routes/rechtliches'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAusgabenRouteImport } from './routes/_authenticated/ausgaben'
import { Route as AuthenticatedBankverbindungRouteImport } from './routes/_authenticated/bankverbindung'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedKalkulationRouteImport } from './routes/_authenticated/kalkulation'
import { Route as AuthenticatedKundenRouteImport } from './routes/_authenticated/kunden'
import { Route as AuthenticatedMeineZeitenRouteImport } from './routes/_authenticated/meine-zeiten'
import { Route as AuthenticatedPersonalRouteImport } from './routes/_authenticated/personal'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedSteuerberaterRouteImport } from './routes/_authenticated/steuerberater'
import { Route as AuthenticatedWiederkehrendRouteImport } from './routes/_authenticated/wiederkehrend'
import { Route as AuthenticatedZeiterfassungRouteImport } from './routes/_authenticated/zeiterfassung'
import { Route as RechtlichesIndexRouteImport } from './routes/rechtliches.index'
import { Route as RechtlichesAgbRouteImport } from './routes/rechtliches.agb'
import { Route as RechtlichesBibliothekenRouteImport } from './routes/rechtliches.bibliotheken'
import { Route as RechtlichesDatenschutzRouteImport } from './routes/rechtliches.datenschutz'
import { Route as RechtlichesImpressumRouteImport } from './routes/rechtliches.impressum'
import { Route as StbTokenRouteImport } from './routes/stb.$token'
import { Route as AuthenticatedDokumenteIndexRouteImport } from './routes/_authenticated/dokumente.index'
import { Route as AuthenticatedDokumenteIdRouteImport } from './routes/_authenticated/dokumente.$id'
import { Route as AuthenticatedProjekteIndexRouteImport } from './routes/_authenticated/projekte.index'
import { Route as AuthenticatedProjekteIdRouteImport } from './routes/_authenticated/projekte.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesRoute = RechtlichesRouteImport.update({
  id: '/rechtliches',
  path: '/rechtliches',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAusgabenRoute = AuthenticatedAusgabenRouteImport.update({
  id: '/ausgaben',
  path: '/ausgaben',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankverbindungRoute =
  AuthenticatedBankverbindungRouteImport.update({
    id: '/bankverbindung',
    path: '/bankverbindung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalkulationRoute =
  AuthenticatedKalkulationRouteImport.update({
    id: '/kalkulation',
    path: '/kalkulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenRoute = AuthenticatedKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeineZeitenRoute =
  AuthenticatedMeineZeitenRouteImport.update({
    id: '/meine-zeiten',
    path: '/meine-zeiten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonalRoute = AuthenticatedPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSteuerberaterRoute =
  AuthenticatedSteuerberaterRouteImport.update({
    id: '/steuerberater',
    path: '/steuerberater',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWiederkehrendRoute =
  AuthenticatedWiederkehrendRouteImport.update({
    id: '/wiederkehrend',
    path: '/wiederkehrend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeiterfassungRoute =
  AuthenticatedZeiterfassungRouteImport.update({
    id: '/zeiterfassung',
    path: '/zeiterfassung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RechtlichesIndexRoute = RechtlichesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesAgbRoute = RechtlichesAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesBibliothekenRoute = RechtlichesBibliothekenRouteImport.update({
  id: '/bibliotheken',
  path: '/bibliotheken',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesDatenschutzRoute = RechtlichesDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesImpressumRoute = RechtlichesImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => RechtlichesRoute,
} as any)
const StbTokenRoute = StbTokenRouteImport.update({
  id: '/stb/$token',
  path: '/stb/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDokumenteIndexRoute =
  AuthenticatedDokumenteIndexRouteImport.update({
    id: '/dokumente/',
    path: '/dokumente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenteIdRoute =
  AuthenticatedDokumenteIdRouteImport.update({
    id: '/dokumente/$id',
    path: '/dokumente/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteIndexRoute =
  AuthenticatedProjekteIndexRouteImport.update({
    id: '/projekte/',
    path: '/projekte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteIdRoute = AuthenticatedProjekteIdRouteImport.update({
  id: '/projekte/$id',
  path: '/projekte/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kalkulation': typeof AuthenticatedKalkulationRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/zeiterfassung': typeof AuthenticatedZeiterfassungRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kalkulation': typeof AuthenticatedKalkulationRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/zeiterfassung': typeof AuthenticatedZeiterfassungRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/dokumente': typeof AuthenticatedDokumenteIndexRoute
  '/projekte': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ausgaben': typeof AuthenticatedAusgabenRoute
  '/_authenticated/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/kalkulation': typeof AuthenticatedKalkulationRoute
  '/_authenticated/kunden': typeof AuthenticatedKundenRoute
  '/_authenticated/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/_authenticated/personal': typeof AuthenticatedPersonalRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/_authenticated/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/_authenticated/zeiterfassung': typeof AuthenticatedZeiterfassungRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/_authenticated/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/_authenticated/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/_authenticated/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/_authenticated/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rechtliches'
    | '/reset-password'
    | '/ausgaben'
    | '/bankverbindung'
    | '/dashboard'
    | '/einstellungen'
    | '/kalkulation'
    | '/kunden'
    | '/meine-zeiten'
    | '/personal'
    | '/profil'
    | '/steuerberater'
    | '/wiederkehrend'
    | '/zeiterfassung'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/dokumente/$id'
    | '/projekte/$id'
    | '/dokumente/'
    | '/projekte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ausgaben'
    | '/bankverbindung'
    | '/dashboard'
    | '/einstellungen'
    | '/kalkulation'
    | '/kunden'
    | '/meine-zeiten'
    | '/personal'
    | '/profil'
    | '/steuerberater'
    | '/wiederkehrend'
    | '/zeiterfassung'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches'
    | '/dokumente/$id'
    | '/projekte/$id'
    | '/dokumente'
    | '/projekte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/rechtliches'
    | '/reset-password'
    | '/_authenticated/ausgaben'
    | '/_authenticated/bankverbindung'
    | '/_authenticated/dashboard'
    | '/_authenticated/einstellungen'
    | '/_authenticated/kalkulation'
    | '/_authenticated/kunden'
    | '/_authenticated/meine-zeiten'
    | '/_authenticated/personal'
    | '/_authenticated/profil'
    | '/_authenticated/steuerberater'
    | '/_authenticated/wiederkehrend'
    | '/_authenticated/zeiterfassung'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/_authenticated/dokumente/$id'
    | '/_authenticated/projekte/$id'
    | '/_authenticated/dokumente/'
    | '/_authenticated/projekte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RechtlichesRoute: typeof RechtlichesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  StbTokenRoute: typeof StbTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches': {
      id: '/rechtliches'
      path: '/rechtliches'
      fullPath: '/rechtliches'
      preLoaderRoute: typeof RechtlichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ausgaben': {
      id: '/_authenticated/ausgaben'
      path: '/ausgaben'
      fullPath: '/ausgaben'
      preLoaderRoute: typeof AuthenticatedAusgabenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bankverbindung': {
      id: '/_authenticated/bankverbindung'
      path: '/bankverbindung'
      fullPath: '/bankverbindung'
      preLoaderRoute: typeof AuthenticatedBankverbindungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalkulation': {
      id: '/_authenticated/kalkulation'
      path: '/kalkulation'
      fullPath: '/kalkulation'
      preLoaderRoute: typeof AuthenticatedKalkulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden': {
      id: '/_authenticated/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof AuthenticatedKundenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meine-zeiten': {
      id: '/_authenticated/meine-zeiten'
      path: '/meine-zeiten'
      fullPath: '/meine-zeiten'
      preLoaderRoute: typeof AuthenticatedMeineZeitenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal': {
      id: '/_authenticated/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AuthenticatedPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/steuerberater': {
      id: '/_authenticated/steuerberater'
      path: '/steuerberater'
      fullPath: '/steuerberater'
      preLoaderRoute: typeof AuthenticatedSteuerberaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wiederkehrend': {
      id: '/_authenticated/wiederkehrend'
      path: '/wiederkehrend'
      fullPath: '/wiederkehrend'
      preLoaderRoute: typeof AuthenticatedWiederkehrendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeiterfassung': {
      id: '/_authenticated/zeiterfassung'
      path: '/zeiterfassung'
      fullPath: '/zeiterfassung'
      preLoaderRoute: typeof AuthenticatedZeiterfassungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/rechtliches/': {
      id: '/rechtliches/'
      path: '/'
      fullPath: '/rechtliches/'
      preLoaderRoute: typeof RechtlichesIndexRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/agb': {
      id: '/rechtliches/agb'
      path: '/agb'
      fullPath: '/rechtliches/agb'
      preLoaderRoute: typeof RechtlichesAgbRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/bibliotheken': {
      id: '/rechtliches/bibliotheken'
      path: '/bibliotheken'
      fullPath: '/rechtliches/bibliotheken'
      preLoaderRoute: typeof RechtlichesBibliothekenRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/datenschutz': {
      id: '/rechtliches/datenschutz'
      path: '/datenschutz'
      fullPath: '/rechtliches/datenschutz'
      preLoaderRoute: typeof RechtlichesDatenschutzRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/impressum': {
      id: '/rechtliches/impressum'
      path: '/impressum'
      fullPath: '/rechtliches/impressum'
      preLoaderRoute: typeof RechtlichesImpressumRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/stb/$token': {
      id: '/stb/$token'
      path: '/stb/$token'
      fullPath: '/stb/$token'
      preLoaderRoute: typeof StbTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dokumente/': {
      id: '/_authenticated/dokumente/'
      path: '/dokumente'
      fullPath: '/dokumente/'
      preLoaderRoute: typeof AuthenticatedDokumenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente/$id': {
      id: '/_authenticated/dokumente/$id'
      path: '/dokumente/$id'
      fullPath: '/dokumente/$id'
      preLoaderRoute: typeof AuthenticatedDokumenteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/': {
      id: '/_authenticated/projekte/'
      path: '/projekte'
      fullPath: '/projekte/'
      preLoaderRoute: typeof AuthenticatedProjekteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/$id': {
      id: '/_authenticated/projekte/$id'
      path: '/projekte/$id'
      fullPath: '/projekte/$id'
      preLoaderRoute: typeof AuthenticatedProjekteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAusgabenRoute: typeof AuthenticatedAusgabenRoute
  AuthenticatedBankverbindungRoute: typeof AuthenticatedBankverbindungRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedKalkulationRoute: typeof AuthenticatedKalkulationRoute
  AuthenticatedKundenRoute: typeof AuthenticatedKundenRoute
  AuthenticatedMeineZeitenRoute: typeof AuthenticatedMeineZeitenRoute
  AuthenticatedPersonalRoute: typeof AuthenticatedPersonalRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSteuerberaterRoute: typeof AuthenticatedSteuerberaterRoute
  AuthenticatedWiederkehrendRoute: typeof AuthenticatedWiederkehrendRoute
  AuthenticatedZeiterfassungRoute: typeof AuthenticatedZeiterfassungRoute
  AuthenticatedDokumenteIdRoute: typeof AuthenticatedDokumenteIdRoute
  AuthenticatedProjekteIdRoute: typeof AuthenticatedProjekteIdRoute
  AuthenticatedDokumenteIndexRoute: typeof AuthenticatedDokumenteIndexRoute
  AuthenticatedProjekteIndexRoute: typeof AuthenticatedProjekteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAusgabenRoute: AuthenticatedAusgabenRoute,
  AuthenticatedBankverbindungRoute: AuthenticatedBankverbindungRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedKalkulationRoute: AuthenticatedKalkulationRoute,
  AuthenticatedKundenRoute: AuthenticatedKundenRoute,
  AuthenticatedMeineZeitenRoute: AuthenticatedMeineZeitenRoute,
  AuthenticatedPersonalRoute: AuthenticatedPersonalRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSteuerberaterRoute: AuthenticatedSteuerberaterRoute,
  AuthenticatedWiederkehrendRoute: AuthenticatedWiederkehrendRoute,
  AuthenticatedZeiterfassungRoute: AuthenticatedZeiterfassungRoute,
  AuthenticatedDokumenteIdRoute: AuthenticatedDokumenteIdRoute,
  AuthenticatedProjekteIdRoute: AuthenticatedProjekteIdRoute,
  AuthenticatedDokumenteIndexRoute: AuthenticatedDokumenteIndexRoute,
  AuthenticatedProjekteIndexRoute: AuthenticatedProjekteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RechtlichesRouteChildren {
  RechtlichesAgbRoute: typeof RechtlichesAgbRoute
  RechtlichesBibliothekenRoute: typeof RechtlichesBibliothekenRoute
  RechtlichesDatenschutzRoute: typeof RechtlichesDatenschutzRoute
  RechtlichesImpressumRoute: typeof RechtlichesImpressumRoute
  RechtlichesIndexRoute: typeof RechtlichesIndexRoute
}

const RechtlichesRouteChildren: RechtlichesRouteChildren = {
  RechtlichesAgbRoute: RechtlichesAgbRoute,
  RechtlichesBibliothekenRoute: RechtlichesBibliothekenRoute,
  RechtlichesDatenschutzRoute: RechtlichesDatenschutzRoute,
  RechtlichesImpressumRoute: RechtlichesImpressumRoute,
  RechtlichesIndexRoute: RechtlichesIndexRoute,
}

const RechtlichesRouteWithChildren = RechtlichesRoute._addFileChildren(
  RechtlichesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RechtlichesRoute: RechtlichesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  StbTokenRoute: StbTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
