/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FreigabeAusstehendRouteImport } from './routes/freigabe-ausstehend'
import { Route as RechtlichesRouteImport } from './routes/rechtliches'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAbonnementsRouteImport } from './routes/_authenticated/abonnements'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAusgabenRouteImport } from './routes/_authenticated/ausgaben'
import { Route as AuthenticatedBankverbindungRouteImport } from './routes/_authenticated/bankverbindung'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedKalkulationRouteImport } from './routes/_authenticated/kalkulation'
import { Route as AuthenticatedKarteRouteImport } from './routes/_authenticated/karte'
import { Route as AuthenticatedMeineZeitenRouteImport } from './routes/_authenticated/meine-zeiten'
import { Route as AuthenticatedNachrichtenRouteImport } from './routes/_authenticated/nachrichten'
import { Route as AuthenticatedPapierkorbRouteImport } from './routes/_authenticated/papierkorb'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedSicherheitRouteImport } from './routes/_authenticated/sicherheit'
import { Route as AuthenticatedSteuerberaterRouteImport } from './routes/_authenticated/steuerberater'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedWiederkehrendRouteImport } from './routes/_authenticated/wiederkehrend'
import { Route as RechtlichesIndexRouteImport } from './routes/rechtliches.index'
import { Route as RechtlichesAgbRouteImport } from './routes/rechtliches.agb'
import { Route as RechtlichesBibliothekenRouteImport } from './routes/rechtliches.bibliotheken'
import { Route as RechtlichesDatenschutzRouteImport } from './routes/rechtliches.datenschutz'
import { Route as RechtlichesImpressumRouteImport } from './routes/rechtliches.impressum'
import { Route as StbTokenRouteImport } from './routes/stb.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDokumenteIndexRouteImport } from './routes/_authenticated/dokumente.index'
import { Route as AuthenticatedDokumenteIdRouteImport } from './routes/_authenticated/dokumente.$id'
import { Route as AuthenticatedKundenIndexRouteImport } from './routes/_authenticated/kunden.index'
import { Route as AuthenticatedKundenIdRouteImport } from './routes/_authenticated/kunden.$id'
import { Route as AuthenticatedProjekteIndexRouteImport } from './routes/_authenticated/projekte.index'
import { Route as AuthenticatedProjekteIdRouteImport } from './routes/_authenticated/projekte.$id'
import { Route as ApiPublicFotoRetentionRouteImport } from './routes/api/public/foto-retention'
import { Route as ApiPublicKontoFreigabeRouteImport } from './routes/api/public/konto-freigabe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FreigabeAusstehendRoute = FreigabeAusstehendRouteImport.update({
  id: '/freigabe-ausstehend',
  path: '/freigabe-ausstehend',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesRoute = RechtlichesRouteImport.update({
  id: '/rechtliches',
  path: '/rechtliches',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAbonnementsRoute =
  AuthenticatedAbonnementsRouteImport.update({
    id: '/abonnements',
    path: '/abonnements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAusgabenRoute = AuthenticatedAusgabenRouteImport.update({
  id: '/ausgaben',
  path: '/ausgaben',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankverbindungRoute =
  AuthenticatedBankverbindungRouteImport.update({
    id: '/bankverbindung',
    path: '/bankverbindung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKalkulationRoute =
  AuthenticatedKalkulationRouteImport.update({
    id: '/kalkulation',
    path: '/kalkulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKarteRoute = AuthenticatedKarteRouteImport.update({
  id: '/karte',
  path: '/karte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeineZeitenRoute =
  AuthenticatedMeineZeitenRouteImport.update({
    id: '/meine-zeiten',
    path: '/meine-zeiten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNachrichtenRoute =
  AuthenticatedNachrichtenRouteImport.update({
    id: '/nachrichten',
    path: '/nachrichten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPapierkorbRoute = AuthenticatedPapierkorbRouteImport.update({
  id: '/papierkorb',
  path: '/papierkorb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSicherheitRoute = AuthenticatedSicherheitRouteImport.update({
  id: '/sicherheit',
  path: '/sicherheit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSteuerberaterRoute =
  AuthenticatedSteuerberaterRouteImport.update({
    id: '/steuerberater',
    path: '/steuerberater',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWiederkehrendRoute =
  AuthenticatedWiederkehrendRouteImport.update({
    id: '/wiederkehrend',
    path: '/wiederkehrend',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RechtlichesIndexRoute = RechtlichesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesAgbRoute = RechtlichesAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesBibliothekenRoute = RechtlichesBibliothekenRouteImport.update({
  id: '/bibliotheken',
  path: '/bibliotheken',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesDatenschutzRoute = RechtlichesDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesImpressumRoute = RechtlichesImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => RechtlichesRoute,
} as any)
const StbTokenRoute = StbTokenRouteImport.update({
  id: '/stb/$token',
  path: '/stb/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDokumenteIndexRoute =
  AuthenticatedDokumenteIndexRouteImport.update({
    id: '/dokumente/',
    path: '/dokumente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenteIdRoute =
  AuthenticatedDokumenteIdRouteImport.update({
    id: '/dokumente/$id',
    path: '/dokumente/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenIndexRoute =
  AuthenticatedKundenIndexRouteImport.update({
    id: '/kunden/',
    path: '/kunden/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenIdRoute = AuthenticatedKundenIdRouteImport.update({
  id: '/kunden/$id',
  path: '/kunden/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjekteIndexRoute =
  AuthenticatedProjekteIndexRouteImport.update({
    id: '/projekte/',
    path: '/projekte/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjekteIdRoute = AuthenticatedProjekteIdRouteImport.update({
  id: '/projekte/$id',
  path: '/projekte/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicFotoRetentionRoute = ApiPublicFotoRetentionRouteImport.update({
  id: '/api/public/foto-retention',
  path: '/api/public/foto-retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKontoFreigabeRoute = ApiPublicKontoFreigabeRouteImport.update({
  id: '/api/public/konto-freigabe',
  path: '/api/public/konto-freigabe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/freigabe-ausstehend': typeof FreigabeAusstehendRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/abonnements': typeof AuthenticatedAbonnementsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kalkulation': typeof AuthenticatedKalkulationRoute
  '/karte': typeof AuthenticatedKarteRoute
  '/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/sicherheit': typeof AuthenticatedSicherheitRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/team': typeof AuthenticatedTeamRoute
  '/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/api/public/foto-retention': typeof ApiPublicFotoRetentionRoute
  '/api/public/konto-freigabe': typeof ApiPublicKontoFreigabeRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/kunden/': typeof AuthenticatedKundenIndexRoute
  '/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/freigabe-ausstehend': typeof FreigabeAusstehendRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/abonnements': typeof AuthenticatedAbonnementsRoute
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kalkulation': typeof AuthenticatedKalkulationRoute
  '/karte': typeof AuthenticatedKarteRoute
  '/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/sicherheit': typeof AuthenticatedSicherheitRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/team': typeof AuthenticatedTeamRoute
  '/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/api/public/foto-retention': typeof ApiPublicFotoRetentionRoute
  '/api/public/konto-freigabe': typeof ApiPublicKontoFreigabeRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dokumente': typeof AuthenticatedDokumenteIndexRoute
  '/kunden': typeof AuthenticatedKundenIndexRoute
  '/projekte': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/freigabe-ausstehend': typeof FreigabeAusstehendRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/abonnements': typeof AuthenticatedAbonnementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ausgaben': typeof AuthenticatedAusgabenRoute
  '/_authenticated/bankverbindung': typeof AuthenticatedBankverbindungRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/kalkulation': typeof AuthenticatedKalkulationRoute
  '/_authenticated/karte': typeof AuthenticatedKarteRoute
  '/_authenticated/meine-zeiten': typeof AuthenticatedMeineZeitenRoute
  '/_authenticated/nachrichten': typeof AuthenticatedNachrichtenRoute
  '/_authenticated/papierkorb': typeof AuthenticatedPapierkorbRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/sicherheit': typeof AuthenticatedSicherheitRoute
  '/_authenticated/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/wiederkehrend': typeof AuthenticatedWiederkehrendRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/_authenticated/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/_authenticated/kunden/$id': typeof AuthenticatedKundenIdRoute
  '/_authenticated/projekte/$id': typeof AuthenticatedProjekteIdRoute
  '/api/public/foto-retention': typeof ApiPublicFotoRetentionRoute
  '/api/public/konto-freigabe': typeof ApiPublicKontoFreigabeRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dokumente/': typeof AuthenticatedDokumenteIndexRoute
  '/_authenticated/kunden/': typeof AuthenticatedKundenIndexRoute
  '/_authenticated/projekte/': typeof AuthenticatedProjekteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/freigabe-ausstehend'
    | '/rechtliches'
    | '/reset-password'
    | '/sitemap.xml'
    | '/abonnements'
    | '/admin'
    | '/ausgaben'
    | '/bankverbindung'
    | '/dashboard'
    | '/einstellungen'
    | '/kalkulation'
    | '/karte'
    | '/meine-zeiten'
    | '/nachrichten'
    | '/papierkorb'
    | '/profil'
    | '/sicherheit'
    | '/steuerberater'
    | '/team'
    | '/wiederkehrend'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/dokumente/$id'
    | '/kunden/$id'
    | '/projekte/$id'
    | '/api/public/foto-retention'
    | '/api/public/konto-freigabe'
    | '/admin/'
    | '/dokumente/'
    | '/kunden/'
    | '/projekte/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/freigabe-ausstehend'
    | '/reset-password'
    | '/sitemap.xml'
    | '/abonnements'
    | '/ausgaben'
    | '/bankverbindung'
    | '/dashboard'
    | '/einstellungen'
    | '/kalkulation'
    | '/karte'
    | '/meine-zeiten'
    | '/nachrichten'
    | '/papierkorb'
    | '/profil'
    | '/sicherheit'
    | '/steuerberater'
    | '/team'
    | '/wiederkehrend'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches'
    | '/dokumente/$id'
    | '/kunden/$id'
    | '/projekte/$id'
    | '/api/public/foto-retention'
    | '/api/public/konto-freigabe'
    | '/admin'
    | '/dokumente'
    | '/kunden'
    | '/projekte'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/freigabe-ausstehend'
    | '/rechtliches'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/abonnements'
    | '/_authenticated/admin'
    | '/_authenticated/ausgaben'
    | '/_authenticated/bankverbindung'
    | '/_authenticated/dashboard'
    | '/_authenticated/einstellungen'
    | '/_authenticated/kalkulation'
    | '/_authenticated/karte'
    | '/_authenticated/meine-zeiten'
    | '/_authenticated/nachrichten'
    | '/_authenticated/papierkorb'
    | '/_authenticated/profil'
    | '/_authenticated/sicherheit'
    | '/_authenticated/steuerberater'
    | '/_authenticated/team'
    | '/_authenticated/wiederkehrend'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/_authenticated/dokumente/$id'
    | '/_authenticated/kunden/$id'
    | '/_authenticated/projekte/$id'
    | '/api/public/foto-retention'
    | '/api/public/konto-freigabe'
    | '/_authenticated/admin/'
    | '/_authenticated/dokumente/'
    | '/_authenticated/kunden/'
    | '/_authenticated/projekte/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FreigabeAusstehendRoute: typeof FreigabeAusstehendRoute
  RechtlichesRoute: typeof RechtlichesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StbTokenRoute: typeof StbTokenRoute
  ApiPublicFotoRetentionRoute: typeof ApiPublicFotoRetentionRoute
  ApiPublicKontoFreigabeRoute: typeof ApiPublicKontoFreigabeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freigabe-ausstehend': {
      id: '/freigabe-ausstehend'
      path: '/freigabe-ausstehend'
      fullPath: '/freigabe-ausstehend'
      preLoaderRoute: typeof FreigabeAusstehendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches': {
      id: '/rechtliches'
      path: '/rechtliches'
      fullPath: '/rechtliches'
      preLoaderRoute: typeof RechtlichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/abonnements': {
      id: '/_authenticated/abonnements'
      path: '/abonnements'
      fullPath: '/abonnements'
      preLoaderRoute: typeof AuthenticatedAbonnementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ausgaben': {
      id: '/_authenticated/ausgaben'
      path: '/ausgaben'
      fullPath: '/ausgaben'
      preLoaderRoute: typeof AuthenticatedAusgabenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bankverbindung': {
      id: '/_authenticated/bankverbindung'
      path: '/bankverbindung'
      fullPath: '/bankverbindung'
      preLoaderRoute: typeof AuthenticatedBankverbindungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kalkulation': {
      id: '/_authenticated/kalkulation'
      path: '/kalkulation'
      fullPath: '/kalkulation'
      preLoaderRoute: typeof AuthenticatedKalkulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/karte': {
      id: '/_authenticated/karte'
      path: '/karte'
      fullPath: '/karte'
      preLoaderRoute: typeof AuthenticatedKarteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meine-zeiten': {
      id: '/_authenticated/meine-zeiten'
      path: '/meine-zeiten'
      fullPath: '/meine-zeiten'
      preLoaderRoute: typeof AuthenticatedMeineZeitenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nachrichten': {
      id: '/_authenticated/nachrichten'
      path: '/nachrichten'
      fullPath: '/nachrichten'
      preLoaderRoute: typeof AuthenticatedNachrichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/papierkorb': {
      id: '/_authenticated/papierkorb'
      path: '/papierkorb'
      fullPath: '/papierkorb'
      preLoaderRoute: typeof AuthenticatedPapierkorbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sicherheit': {
      id: '/_authenticated/sicherheit'
      path: '/sicherheit'
      fullPath: '/sicherheit'
      preLoaderRoute: typeof AuthenticatedSicherheitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/steuerberater': {
      id: '/_authenticated/steuerberater'
      path: '/steuerberater'
      fullPath: '/steuerberater'
      preLoaderRoute: typeof AuthenticatedSteuerberaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wiederkehrend': {
      id: '/_authenticated/wiederkehrend'
      path: '/wiederkehrend'
      fullPath: '/wiederkehrend'
      preLoaderRoute: typeof AuthenticatedWiederkehrendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/rechtliches/': {
      id: '/rechtliches/'
      path: '/'
      fullPath: '/rechtliches/'
      preLoaderRoute: typeof RechtlichesIndexRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/agb': {
      id: '/rechtliches/agb'
      path: '/agb'
      fullPath: '/rechtliches/agb'
      preLoaderRoute: typeof RechtlichesAgbRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/bibliotheken': {
      id: '/rechtliches/bibliotheken'
      path: '/bibliotheken'
      fullPath: '/rechtliches/bibliotheken'
      preLoaderRoute: typeof RechtlichesBibliothekenRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/datenschutz': {
      id: '/rechtliches/datenschutz'
      path: '/datenschutz'
      fullPath: '/rechtliches/datenschutz'
      preLoaderRoute: typeof RechtlichesDatenschutzRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/impressum': {
      id: '/rechtliches/impressum'
      path: '/impressum'
      fullPath: '/rechtliches/impressum'
      preLoaderRoute: typeof RechtlichesImpressumRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/stb/$token': {
      id: '/stb/$token'
      path: '/stb/$token'
      fullPath: '/stb/$token'
      preLoaderRoute: typeof StbTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/dokumente/': {
      id: '/_authenticated/dokumente/'
      path: '/dokumente'
      fullPath: '/dokumente/'
      preLoaderRoute: typeof AuthenticatedDokumenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente/$id': {
      id: '/_authenticated/dokumente/$id'
      path: '/dokumente/$id'
      fullPath: '/dokumente/$id'
      preLoaderRoute: typeof AuthenticatedDokumenteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden/': {
      id: '/_authenticated/kunden/'
      path: '/kunden'
      fullPath: '/kunden/'
      preLoaderRoute: typeof AuthenticatedKundenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden/$id': {
      id: '/_authenticated/kunden/$id'
      path: '/kunden/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof AuthenticatedKundenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/': {
      id: '/_authenticated/projekte/'
      path: '/projekte'
      fullPath: '/projekte/'
      preLoaderRoute: typeof AuthenticatedProjekteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projekte/$id': {
      id: '/_authenticated/projekte/$id'
      path: '/projekte/$id'
      fullPath: '/projekte/$id'
      preLoaderRoute: typeof AuthenticatedProjekteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/foto-retention': {
      id: '/api/public/foto-retention'
      path: '/api/public/foto-retention'
      fullPath: '/api/public/foto-retention'
      preLoaderRoute: typeof ApiPublicFotoRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/konto-freigabe': {
      id: '/api/public/konto-freigabe'
      path: '/api/public/konto-freigabe'
      fullPath: '/api/public/konto-freigabe'
      preLoaderRoute: typeof ApiPublicKontoFreigabeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbonnementsRoute: typeof AuthenticatedAbonnementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAusgabenRoute: typeof AuthenticatedAusgabenRoute
  AuthenticatedBankverbindungRoute: typeof AuthenticatedBankverbindungRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedKalkulationRoute: typeof AuthenticatedKalkulationRoute
  AuthenticatedKarteRoute: typeof AuthenticatedKarteRoute
  AuthenticatedMeineZeitenRoute: typeof AuthenticatedMeineZeitenRoute
  AuthenticatedNachrichtenRoute: typeof AuthenticatedNachrichtenRoute
  AuthenticatedPapierkorbRoute: typeof AuthenticatedPapierkorbRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSicherheitRoute: typeof AuthenticatedSicherheitRoute
  AuthenticatedSteuerberaterRoute: typeof AuthenticatedSteuerberaterRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedWiederkehrendRoute: typeof AuthenticatedWiederkehrendRoute
  AuthenticatedDokumenteIdRoute: typeof AuthenticatedDokumenteIdRoute
  AuthenticatedKundenIdRoute: typeof AuthenticatedKundenIdRoute
  AuthenticatedProjekteIdRoute: typeof AuthenticatedProjekteIdRoute
  AuthenticatedDokumenteIndexRoute: typeof AuthenticatedDokumenteIndexRoute
  AuthenticatedKundenIndexRoute: typeof AuthenticatedKundenIndexRoute
  AuthenticatedProjekteIndexRoute: typeof AuthenticatedProjekteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbonnementsRoute: AuthenticatedAbonnementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAusgabenRoute: AuthenticatedAusgabenRoute,
  AuthenticatedBankverbindungRoute: AuthenticatedBankverbindungRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedKalkulationRoute: AuthenticatedKalkulationRoute,
  AuthenticatedKarteRoute: AuthenticatedKarteRoute,
  AuthenticatedMeineZeitenRoute: AuthenticatedMeineZeitenRoute,
  AuthenticatedNachrichtenRoute: AuthenticatedNachrichtenRoute,
  AuthenticatedPapierkorbRoute: AuthenticatedPapierkorbRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSicherheitRoute: AuthenticatedSicherheitRoute,
  AuthenticatedSteuerberaterRoute: AuthenticatedSteuerberaterRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedWiederkehrendRoute: AuthenticatedWiederkehrendRoute,
  AuthenticatedDokumenteIdRoute: AuthenticatedDokumenteIdRoute,
  AuthenticatedKundenIdRoute: AuthenticatedKundenIdRoute,
  AuthenticatedProjekteIdRoute: AuthenticatedProjekteIdRoute,
  AuthenticatedDokumenteIndexRoute: AuthenticatedDokumenteIndexRoute,
  AuthenticatedKundenIndexRoute: AuthenticatedKundenIndexRoute,
  AuthenticatedProjekteIndexRoute: AuthenticatedProjekteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RechtlichesRouteChildren {
  RechtlichesAgbRoute: typeof RechtlichesAgbRoute
  RechtlichesBibliothekenRoute: typeof RechtlichesBibliothekenRoute
  RechtlichesDatenschutzRoute: typeof RechtlichesDatenschutzRoute
  RechtlichesImpressumRoute: typeof RechtlichesImpressumRoute
  RechtlichesIndexRoute: typeof RechtlichesIndexRoute
}

const RechtlichesRouteChildren: RechtlichesRouteChildren = {
  RechtlichesAgbRoute: RechtlichesAgbRoute,
  RechtlichesBibliothekenRoute: RechtlichesBibliothekenRoute,
  RechtlichesDatenschutzRoute: RechtlichesDatenschutzRoute,
  RechtlichesImpressumRoute: RechtlichesImpressumRoute,
  RechtlichesIndexRoute: RechtlichesIndexRoute,
}

const RechtlichesRouteWithChildren = RechtlichesRoute._addFileChildren(
  RechtlichesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FreigabeAusstehendRoute: FreigabeAusstehendRoute,
  RechtlichesRoute: RechtlichesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StbTokenRoute: StbTokenRoute,
  ApiPublicFotoRetentionRoute: ApiPublicFotoRetentionRoute,
  ApiPublicKontoFreigabeRoute: ApiPublicKontoFreigabeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
