/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RechtlichesRouteImport } from './routes/rechtliches'
import { Route as AuthenticatedAusgabenRouteImport } from './routes/_authenticated/ausgaben'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEinstellungenRouteImport } from './routes/_authenticated/einstellungen'
import { Route as AuthenticatedKundenRouteImport } from './routes/_authenticated/kunden'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedSteuerberaterRouteImport } from './routes/_authenticated/steuerberater'
import { Route as RechtlichesIndexRouteImport } from './routes/rechtliches.index'
import { Route as RechtlichesAgbRouteImport } from './routes/rechtliches.agb'
import { Route as RechtlichesBibliothekenRouteImport } from './routes/rechtliches.bibliotheken'
import { Route as RechtlichesDatenschutzRouteImport } from './routes/rechtliches.datenschutz'
import { Route as RechtlichesImpressumRouteImport } from './routes/rechtliches.impressum'
import { Route as StbTokenRouteImport } from './routes/stb.$token'
import { Route as AuthenticatedDokumenteIndexRouteImport } from './routes/_authenticated/dokumente.index'
import { Route as AuthenticatedDokumenteIdRouteImport } from './routes/_authenticated/dokumente.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RechtlichesRoute = RechtlichesRouteImport.update({
  id: '/rechtliches',
  path: '/rechtliches',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAusgabenRoute = AuthenticatedAusgabenRouteImport.update({
  id: '/ausgaben',
  path: '/ausgaben',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEinstellungenRoute =
  AuthenticatedEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKundenRoute = AuthenticatedKundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSteuerberaterRoute =
  AuthenticatedSteuerberaterRouteImport.update({
    id: '/steuerberater',
    path: '/steuerberater',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const RechtlichesIndexRoute = RechtlichesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesAgbRoute = RechtlichesAgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesBibliothekenRoute = RechtlichesBibliothekenRouteImport.update({
  id: '/bibliotheken',
  path: '/bibliotheken',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesDatenschutzRoute = RechtlichesDatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => RechtlichesRoute,
} as any)
const RechtlichesImpressumRoute = RechtlichesImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => RechtlichesRoute,
} as any)
const StbTokenRoute = StbTokenRouteImport.update({
  id: '/stb/$token',
  path: '/stb/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDokumenteIndexRoute =
  AuthenticatedDokumenteIndexRouteImport.update({
    id: '/dokumente/',
    path: '/dokumente/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDokumenteIdRoute =
  AuthenticatedDokumenteIdRouteImport.update({
    id: '/dokumente/$id',
    path: '/dokumente/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/dokumente/': typeof AuthenticatedDokumenteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ausgaben': typeof AuthenticatedAusgabenRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/kunden': typeof AuthenticatedKundenRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches': typeof RechtlichesIndexRoute
  '/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/dokumente': typeof AuthenticatedDokumenteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/rechtliches': typeof RechtlichesRouteWithChildren
  '/_authenticated/ausgaben': typeof AuthenticatedAusgabenRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/einstellungen': typeof AuthenticatedEinstellungenRoute
  '/_authenticated/kunden': typeof AuthenticatedKundenRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/steuerberater': typeof AuthenticatedSteuerberaterRoute
  '/rechtliches/agb': typeof RechtlichesAgbRoute
  '/rechtliches/bibliotheken': typeof RechtlichesBibliothekenRoute
  '/rechtliches/datenschutz': typeof RechtlichesDatenschutzRoute
  '/rechtliches/impressum': typeof RechtlichesImpressumRoute
  '/stb/$token': typeof StbTokenRoute
  '/rechtliches/': typeof RechtlichesIndexRoute
  '/_authenticated/dokumente/$id': typeof AuthenticatedDokumenteIdRoute
  '/_authenticated/dokumente/': typeof AuthenticatedDokumenteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rechtliches'
    | '/ausgaben'
    | '/dashboard'
    | '/einstellungen'
    | '/kunden'
    | '/profil'
    | '/steuerberater'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/dokumente/$id'
    | '/dokumente/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ausgaben'
    | '/dashboard'
    | '/einstellungen'
    | '/kunden'
    | '/profil'
    | '/steuerberater'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches'
    | '/dokumente/$id'
    | '/dokumente'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/rechtliches'
    | '/_authenticated/ausgaben'
    | '/_authenticated/dashboard'
    | '/_authenticated/einstellungen'
    | '/_authenticated/kunden'
    | '/_authenticated/profil'
    | '/_authenticated/steuerberater'
    | '/rechtliches/agb'
    | '/rechtliches/bibliotheken'
    | '/rechtliches/datenschutz'
    | '/rechtliches/impressum'
    | '/stb/$token'
    | '/rechtliches/'
    | '/_authenticated/dokumente/$id'
    | '/_authenticated/dokumente/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RechtlichesRoute: typeof RechtlichesRouteWithChildren
  StbTokenRoute: typeof StbTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechtliches': {
      id: '/rechtliches'
      path: '/rechtliches'
      fullPath: '/rechtliches'
      preLoaderRoute: typeof RechtlichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ausgaben': {
      id: '/_authenticated/ausgaben'
      path: '/ausgaben'
      fullPath: '/ausgaben'
      preLoaderRoute: typeof AuthenticatedAusgabenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/einstellungen': {
      id: '/_authenticated/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof AuthenticatedEinstellungenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kunden': {
      id: '/_authenticated/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof AuthenticatedKundenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/steuerberater': {
      id: '/_authenticated/steuerberater'
      path: '/steuerberater'
      fullPath: '/steuerberater'
      preLoaderRoute: typeof AuthenticatedSteuerberaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/rechtliches/': {
      id: '/rechtliches/'
      path: '/'
      fullPath: '/rechtliches/'
      preLoaderRoute: typeof RechtlichesIndexRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/agb': {
      id: '/rechtliches/agb'
      path: '/agb'
      fullPath: '/rechtliches/agb'
      preLoaderRoute: typeof RechtlichesAgbRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/bibliotheken': {
      id: '/rechtliches/bibliotheken'
      path: '/bibliotheken'
      fullPath: '/rechtliches/bibliotheken'
      preLoaderRoute: typeof RechtlichesBibliothekenRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/datenschutz': {
      id: '/rechtliches/datenschutz'
      path: '/datenschutz'
      fullPath: '/rechtliches/datenschutz'
      preLoaderRoute: typeof RechtlichesDatenschutzRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/rechtliches/impressum': {
      id: '/rechtliches/impressum'
      path: '/impressum'
      fullPath: '/rechtliches/impressum'
      preLoaderRoute: typeof RechtlichesImpressumRouteImport
      parentRoute: typeof RechtlichesRoute
    }
    '/stb/$token': {
      id: '/stb/$token'
      path: '/stb/$token'
      fullPath: '/stb/$token'
      preLoaderRoute: typeof StbTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dokumente/': {
      id: '/_authenticated/dokumente/'
      path: '/dokumente'
      fullPath: '/dokumente/'
      preLoaderRoute: typeof AuthenticatedDokumenteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dokumente/$id': {
      id: '/_authenticated/dokumente/$id'
      path: '/dokumente/$id'
      fullPath: '/dokumente/$id'
      preLoaderRoute: typeof AuthenticatedDokumenteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAusgabenRoute: typeof AuthenticatedAusgabenRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEinstellungenRoute: typeof AuthenticatedEinstellungenRoute
  AuthenticatedKundenRoute: typeof AuthenticatedKundenRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedSteuerberaterRoute: typeof AuthenticatedSteuerberaterRoute
  AuthenticatedDokumenteIdRoute: typeof AuthenticatedDokumenteIdRoute
  AuthenticatedDokumenteIndexRoute: typeof AuthenticatedDokumenteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAusgabenRoute: AuthenticatedAusgabenRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEinstellungenRoute: AuthenticatedEinstellungenRoute,
  AuthenticatedKundenRoute: AuthenticatedKundenRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedSteuerberaterRoute: AuthenticatedSteuerberaterRoute,
  AuthenticatedDokumenteIdRoute: AuthenticatedDokumenteIdRoute,
  AuthenticatedDokumenteIndexRoute: AuthenticatedDokumenteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RechtlichesRouteChildren {
  RechtlichesAgbRoute: typeof RechtlichesAgbRoute
  RechtlichesBibliothekenRoute: typeof RechtlichesBibliothekenRoute
  RechtlichesDatenschutzRoute: typeof RechtlichesDatenschutzRoute
  RechtlichesImpressumRoute: typeof RechtlichesImpressumRoute
  RechtlichesIndexRoute: typeof RechtlichesIndexRoute
}

const RechtlichesRouteChildren: RechtlichesRouteChildren = {
  RechtlichesAgbRoute: RechtlichesAgbRoute,
  RechtlichesBibliothekenRoute: RechtlichesBibliothekenRoute,
  RechtlichesDatenschutzRoute: RechtlichesDatenschutzRoute,
  RechtlichesImpressumRoute: RechtlichesImpressumRoute,
  RechtlichesIndexRoute: RechtlichesIndexRoute,
}

const RechtlichesRouteWithChildren = RechtlichesRoute._addFileChildren(
  RechtlichesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RechtlichesRoute: RechtlichesRouteWithChildren,
  StbTokenRoute: StbTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
