-- Restore the storage used by consume_mail_budget.
-- The throttle RPC was deployed without its backing table, causing every
-- authenticated document email to be rejected as if the rate limit was hit.

CREATE TABLE IF NOT EXISTS public.auth_mail_throttle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL CHECK (scope IN ('email','ip')),
  key_hash text NOT NULL CHECK (key_hash ~ '^[a-f0-9]{64}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS auth_mail_throttle_lookup_idx
  ON public.auth_mail_throttle (scope, key_hash, created_at DESC);

ALTER TABLE public.auth_mail_throttle ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.auth_mail_throttle FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.auth_mail_throttle TO service_role;

-- Older/local schemas may already contain the throttle table without the
-- identity column used by the production repair. Grant sequence access only
-- when that sequence exists so a full migration replay remains compatible.
DO $$
BEGIN
  IF to_regclass('public.auth_mail_throttle_id_seq') IS NOT NULL THEN
    GRANT USAGE, SELECT ON SEQUENCE public.auth_mail_throttle_id_seq TO service_role;
  END IF;
END $$;
